name: Hello World Workflow
on: [push]  # Triggers the workflow every time you push code
jobs:
  say-hello:
    runs-on: ubuntu-latest
    outputs:
      my_shared_var: ${{steps.hi.outputs.test_value}}
    steps:
      - name: Greet the world
        id: hi
        run: echo "test_value=Hello, World!" >> $GITHUB_OUTPUT
      
  checkout-code:
    runs-on: ubuntu-latest
    needs: say-hello
    
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
      - name: find the path
        run: pwd
      - name: list the files
        run: ls -ltr
      - name: use value from say_hello
        run: echo "${{needs.say-hello.outputs.my_shared_var }}, $newvar"
        env:
          newvar: Hooray!

  call-triggered-workflow:
    needs: checkout-code
    uses: ./.github/workflows/TriggeredWorkFlow.yml
    with:
      hi_var: "hi"

  call-output-from-triggered-workflow: 
    needs: call-triggered-workflow
    runs-on: ubuntu-latest
    steps: 
      - name: getting TriggeredWorkFlow output
        run: echo ${{needs.call-Triggered-workflow.outputs.out_var}} 
      - name: getting TriggeredWorkFlow output sum
        run: echo ${{needs.call-Triggered-workflow.outputs.out_sum}}

   
  
  


