# my-org/triggered-repo/.github/workflows/triggered-workflow.yml
name: Triggered Workflow

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      my_output: ${{steps.set.outputs.msg}}
    steps:
      - name: Run a script
        id: set
        run: echo "msg=This is the triggered workflow" >>GITHUB_OUTPUT






