# my-org/triggered-repo/.github/workflows/triggered-workflow.yml
name: Triggered Workflow

on:
  workflow_call:
    inputs: 
      hi_var: 
        required: true
        type: string
    outputs: 
      out_var: ${{jobs.build.outputs.my_output}}


jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      my_output: ${{steps.setvar.outputs.msg}}
    steps:
      - run: echo "${{ inputs.hi_var }}" 
        name: print the input
      - name: Run a script
        id: setvar
        run: echo "msg=This is the triggered workflow" >>$GITHUB_OUTPUT


